name: "Label Pull Requests"

on:
- pull_request_target

jobs:
  label-pull-requests:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/labeler@v4