name: Update Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: self-hosted
    steps:
      - name: Update Release
        uses: google-github-actions/release-please-action@v3
        id: "google"
        with:
          command: manifest
      - name: Update Tags
        uses: actions/checkout@v3
      - uses: ./.github/actions/add_tags
