name: "System Tests"

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  label-pull-requests:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/labeler@v4
    - uses: .github/workflows/test-cli.yml
    - uses: .github/workflows/test-explorer.yml