name: CLI Tests

on:
  push:
    branches: [main]
  pull_request:
    types: [labeled]
  workflow_call:

jobs:
  texttools_cli:
    if: |
      github.event_name == 'workflow_call' || 
      github.event_name == 'push' || 
      contains(github.event.pull_request.labels.*.name, 'Schema CLI')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install CLI
      run: |
        pip install "./cli"
        pip list -v
    - name: Test CLI
      run: |
        validate-text -t "1233 asdasd"
        validate-text -t "1233asdasd"
        compile-text -t "1234 asdasd"