name: Explorer Tests

on:
  push:
    branches: [main]
  pull_request:
    types: [labeled]
  workflow_run:
    workflows: ["Label Pull Requests"]
    types: [completed]

jobs:
  texttools_cli:
    if: |
      github.event_name == 'workflow_run' ||
      github.event_name == 'push' ||
      contains(github.event.pull_request.labels.*.name, 'Schema Explorer')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Explorer
      run: |
        pip install "./explorer"
        pip list -v
    - name: Test Explorer
      run: |
        generate-page -t "Hello World\!"